<?php
	
	$professor_names=array("AFRASIABI, P.",
		"AREWA, O.",
		"AUGUSTINIAK, E.",
		"BALTA, A.",
		"BARNES, M.",
		"BROWN, A.",
		"BROWN, MICHAEL",
		"BURK, D.",
		"CAMACHO, A.",
		"CAPOCCIA, R.",
		"CARLISLE, C.",
		"CARNEY, C.",
		"CEBALLOS, R.",
		"CHEMERINSKY, E.",
		"COOKE, S.",
		"CROSKERY-ROBERTS, R.",
		"CYR, P.",
		"DAVIS, K.",
		"DIMENTO, J.",
		"DUNN, J.",
		"EBADOLAHI, M.",
		"FISK, C.",
		"GAGNIER, C.",
		"GARTH, B.",
		"GESSIN, J.",
		"GOLDSTONE, R.",
		"GOMEZ, C.",
		"GOODWIN, M.",
		"GUILFORD, A.",
		"HASEN, R.",
		"HEMPEL, C.",
		"HOFFMAN, P.",
		"HURWITZ, L.",
		"JUNGHAHN, L.",
		"KAYE, D.",
		"KIM, S.",
		"KUNG, S",
		"LA TERZA, N.",
		"LAI, A.",
		"LAWSKY, S.",
		"LEE, S.",
		"LEHTMAN, N.",
		"LERNER, J.",
		"LESLIE, C.",
		"LOFTUS, E.",
		"LUZ, A.",
		"MACLEAN, E.",
		"MARIAN, O",
		"MENKEL-MEADOW, C.",
		"MEYER, J.",
		"MIN, D.",
		"NGUYEN, G.",
		"PEESAPATI, S.",
		"PEJAN, R.",
		"PORTER, K.",
		"PUERTAS, L.",
		"REESE, R.",
		"REITER, K.",
		"RIDDLE, L.",
		"ROSENBAUM, M.",
		"ROSENBERG, S.",
		"ROSS, E.",
		"SCHAEFER, M.",
		"SCHUMANN, T.",
		"SEPLOW, M.",
		"SHAFFER, G.",
		"SIMONS, K.",
		"SIMS, C.",
		"SOLOMON, R.",
		"SONI, M.",
		"SOUTHWORTH, A.",
		"SPANGLER, T.",
		"SWEETSER, C.",
		"TALESH, S.",
		"TATE, W.",
		"TICE, B.",
		"TONNER, G.",
		"TSOU, C.",
		"UBINK, J.",
		"VAN ROOIJ, B.",
		"WALD, J.",
		"WEINSTEIN, H.",
		"WHYTOCK, C.",
		"WIMER, J.",
		"WOODSIDE, J.");
		
		foreach ($professor_names as $item) {
			echo '<option value="'.$item.'">'.$item.'</option>';
		}
				
?>